### ISSUE TITLE
React native SDK issue on Monorepo

### ISSUE THREAD

**Issue by master96** [launchdarkly/js-core#412] opened 2024-03-28 19:09 UTC
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the code in this library. If you're not sure whether the problem you are having is specifically related to this library, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
error: Error: Unable to resolve module event-target-shim/es5 from /Users/vajage/Desktop/***/packages/native/node_modules/@launchdarkly/react-native-client-sdk/dist/src/polyfills/CustomEvent.js: event-target-shim/es5 could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  
**To reproduce**
Install Launchdarkly on monorepo with react and react-native

**Expected behavior**

**Logs**
error: Error: Unable to resolve module event-target-shim/es5 from /Users/vajage/Desktop/provider-platform-app/packages/native/node_modules/@launchdarkly/react-native-client-sdk/dist/src/polyfills/CustomEvent.js: event-target-shim/es5 could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  3 |  * https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Events/CustomEvent.js#L21
  4 |  */
> 5 | import { Event } from 'event-target-shim/es5';

**SDK version**
^10.0.5

**Language version, developer tools**
"react-native": "0.72.4"

**OS/platform**
Mac 

**Additional context**

**Comment by yusinto** [comment] 2024-04-01 17:32
@master96 Please provide more information; what kind of monorepo tool are you using? And please provide a minimal reproducible project which demonstrates the bug so I can reproduce. Thank you.

**Comment by navignaw** [comment] 2024-05-09 03:12
Seeing the same issue with a yarn (classic) workspace. We have a monorepo set up with both Expo and Next.js, though I'm not sure how relevant the latter is. I did some research and it looks like there is an alternative polyfill that we could try: https://github.com/facebook/react-native/issues/38004#issuecomment-1714210503

I'm not really sure if importing `event-target-shim/es5` makes sense on React Native since according to the docs, it's primarily for IE11:

> If you want to support IE11, use import {} from "event-target-shim/es5" instead. It's a transpiled code by babel. It depends on @baebl/runtime (^7.12.0) package.

Also, fwiw, the [link in the code](https://github.com/launchdarkly/js-core/blob/0c1302f14b39b276d23e5e65aa5f5ad57ec32161/packages/sdk/react-native/src/polyfills/CustomEvent.ts#L3) points to a new React Native implementation that no longer uses `event-target-shim`, but rather implements its own polyfill.

**Comment by navignaw** [comment] 2024-06-19 22:58
I was able to fix this by removing the `event-target-shim/es5` code and instead replacing it with the latest polyfill from react-native.

In particular, I copied over these two files on the latest main: [EventPolyfill.js](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Events/EventPolyfill.js) and [CustomEvent.js](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Events/CustomEvent.js), thanks to the comment [here](https://github.com/launchdarkly/js-core/blob/0c1302f14b39b276d23e5e65aa5f5ad57ec32161/packages/sdk/react-native/src/polyfills/CustomEvent.ts#L3). This removed the dependency on `event-target-shim/es5` and successfully solved the problem. However because I patched the JS files directly it's not clear to me whether this passes typechecking (as the source files are written with Flow instead of TypeScript).

If this is an acceptable solution, I'd love to see it merged upstream.

**Comment by navignaw** [comment] 2024-07-02 00:54
@yusinto would you be okay with the proposal in my comment above, swapping out the outdated polyfill with the latest code from react-native? I could put together a PR if that would help.

**Comment by kinyoklion** [comment] 2024-07-19 17:52
Hello @navignaw,

Thank you for the feedback. So far I have not been able to reproduce anything similar. We will look into the suitability of the event target shim.

Thank you,
Ryan

**Comment by navignaw** [comment] 2024-07-23 04:05
I was finally able to make some progress! For some reason, the hoisted `event-target-shim` library in `node_modules` was getting installed with version 5.0.1 which was missing the `es5` file. By explicitly forcing the version to 6.0.2 in my package.json, I was able to bypass the issue!

```json
// package.json
{
  "event-target-shim": "^6.0.2"
}
```

It turns out that some other libraries, including [react-native](https://github.com/facebook/react-native/blob/main/packages/react-native/package.json#L127), really wanted 5.0.1 installed:

```
yarn why "event-target-shim"

...
├─ abort-controller@npm:3.0.0
│  └─ event-target-shim@npm:5.0.1 (via npm:^5.0.0)
└─ react-native@npm:0.73.8 
   └─ event-target-shim@npm:5.0.1 (via npm:^5.0.1)
```

I'm not sure if OP had the same issue, but I think we can likely close this out as a silly artifact of yarn hoisting, not a bug with the library. Though I still think my suggestion of removing the dependency entirely would be nice, especially since it's using an incompatible version as react-native.

**Closed** 2024-08-15 19:11 UTC
Labels: bug, waiting for feedback, package: sdk/react-native
