### ISSUE TITLE
Issue running with the example code from the node redis integration.

### ISSUE THREAD

**Issue by kikar** [launchdarkly/js-core#568] opened 2024-09-05 08:52 UTC
**Describe the bug**
The example provided in the README.md is not working

**To reproduce**
```ts
import { init } from '@launchdarkly/node-server-sdk';
import { RedisFeatureStore } from '@launchdarkly/node-server-sdk-redis';

(async function main() {
  const client = init(process.env.LD_KEY!, {
    featureStore: RedisFeatureStore(),
  });
  await client.waitForInitialization({ timeout: 5 });
})();
```

**Expected behavior**
Not to throw errors

**Logs**
```
~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/serialization.js:42
    if (value.generated_includedSet) {
              ^

TypeError: Cannot read properties of undefined (reading 'generated_includedSet')
    at Array.replacer (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/serialization.js:42:15)
    at JSON.stringify (<anonymous>)
    at serializeFlag (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/serialization.js:248:17)
    at Object.serialize (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/persistentStoreKinds.js:45:70)
    at visit (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:34:24)
    at topologicalSort (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:40:9)
    at ~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:59:40
    at Array.forEach (<anonymous>)
    at sortDataSet (~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/sortDataSet.js:57:26)
    at ~/Developer/test/node_modules/@launchdarkly/js-server-sdk-common/dist/store/PersistentDataStoreWrapper.js:107:54
```
**SDK version**
- @launchdarkly/node-server-sdk: 9.5.3
- @launchdarkly/node-server-sdk-redis: 4.1.20

**Language version, developer tools**
Node: 20.17.0

**OS/platform**
Mac OS Sonoma 14.6.1 (23G93)

**Comment by kinyoklion** [comment] 2024-09-05 15:52
Hello @kikar,

Thank you for the report. I am able to run the example code without issue.

Is this an existing project that is being updated? A new project with just that confiuration?

Are you using a redis instance that is already initialized with some data from a previous version?

My initial suspicion would be to ensure that the dependencies for the common libraries are also matching the expected versions.

I've attached the lockfile from running the example.
[package-lock.json](https://github.com/user-attachments/files/16897107/package-lock.json)

Thank you,
Ryan

**Comment by kikar** [comment] 2024-09-05 16:11
Hi @kinyoklion , thank you for the reply.
I've added a small example repo, including a compose file for redis: https://github.com/kikar/ld-redis-test

- This is a new project and new redis initalised instance.
- Using Node 20.17.0 with npm 10.8.2
- Yes, SDK initialises correctly once removed the featureStore
- You can find in the repo also package-lock.json with all the dependencies which are both the latest version of LD.

**Comment by kinyoklion** [comment] 2024-09-05 16:36
@kikar 

I tried your example in a Github codespace and it worked fine.

It had:
```
@kinyoklion ➜ /workspaces/ld-redis-test (master) $ node --version
v20.16.0
@kinyoklion ➜ /workspaces/ld-redis-test (master) $ npm --version
10.8.1
```

I do see you are using macOS, but that shouldn't be causing a problem like this.

Can you let me know if it works in a code space? If it does, then this would help to eliminate your specific flag configuration from being the source of the problem, and instead indicate a problem with your development environment.

Thank you,
Ryan

**Comment by kikar** [comment] 2024-09-05 16:50
@kinyoklion I added docker compose full reproduction steps, and still doesn't work. That should take out of the problem my machine (unless related to arm architecture). Check the README

Does it reproduce for you with the `docker compose up` command?

I will try to use the node/npm versions specified by your test

**Comment by kinyoklion** [comment] 2024-09-05 16:54
I used docker compose up in the codespace.

What is in the LD environment you are using for testing? Is this an existing environment populated with flags, empty, etc?

**Comment by kikar** [comment] 2024-09-05 16:55
Is our company testing env, already populated with flags

**Comment by kinyoklion** [comment] 2024-09-05 17:00
The only difference would be the project/environment.
![image](https://github.com/user-attachments/assets/10b7494c-1da8-493e-ad93-5386d833f591)

Would it be possible for you to try a different project? If a different project works, and your companies test environment does not, then you will need to raise a support ticket. We would need to see what data is causing the misbehavior. 

Thank you,
Ryan

**Comment by kinyoklion** [comment] 2024-09-05 17:01
In the interim I can investigate and see if some additional safety checks are warranted.

**Comment by kikar** [comment] 2024-09-05 17:09
@kinyoklion I created a new project, and now the SDK key works!

![image](https://github.com/user-attachments/assets/8de9ddfa-25e2-4671-80e5-fd4b3ccd585d)

**Comment by kinyoklion** [comment] 2024-09-05 17:12
@kikar 

Thank you!

I figured out what the likely problem is and will make a patch.

The issue is encountered with JSON flags which are arrays and which contain null/undefined values.

```
[
  1,
  null,
  "potato"
]
```

It doesn't happen in most environments because this is not very typical. It also only happens with a persistent store integration because the SDK is re-serializing values to store in persistence.

Thank you for your report and help.

- Ryan

**Comment by kinyoklion** [comment] 2024-09-05 17:14
_Filed internally as 255288_

**Comment by kinyoklion** [comment] 2024-09-05 17:23
@kikar 

The ticket will update when the fix PR is merged, and then I will release shortly after that. I can make a comment on the ticket at that time as well.

I think it would be best to start with support for your account representative for the `null` variation setting. Currently the JSON variations only support arrays or objects. If you have problems with that route, then let me know and I will see what I can do.

Thank you,
Ryan

**Closed** 2024-09-05 20:55 UTC
Labels: bug, package: sdk/server-node, package: store/node-server-sdk-redis

**Comment by kinyoklion** [comment] 2024-09-05 22:21
@kikar I have released `@launchdarkly/node-server-sdk` version 9.5.4 which includes the fix for this issue.

Thank you,
Ryan
